projects:
  - name: FoxRunner
    url: http://localhost:4200
    backend:
      path: D:\PycharmProjects\FoxRunner_server
      venv: .venv
      command: python manage.py runserver 8000
      port: 8000
    frontend:
      path: C:\Users\Renaud\WebstormProjects\FoxRunner_frontend
      command: ng serve --port 4200
      port: 4200

  - name: QuizOnline
    url: http://localhost:4200
    backend:
      path: D:\PycharmProjects\QuizOnline\quizonline-server
      venv: ..\.venv
      command: python manage.py runserver 8000
      port: 8000
    frontend:
      path: D:\PycharmProjects\QuizOnline\quizonline-frontend
      command: ng serve --port 4200
      port: 4200

  - name: PushIT
    url: http://localhost:4200
    backend:
      path: D:\PycharmProjects\PushIT_server
      venv: .venv
      command: python manage.py runserver 8000
      port: 8000
    frontend:
      path: C:\Users\Renaud\WebstormProjects\PushIT_frontend
      command: ng serve --port 4200
      port: 4200
